name             'mysql-mha'
maintainer       'Ovais Tariq'
maintainer_email 'me@ovaistariq.net'
license          'Apache 2.0'
description      'Installs/Configures MHA and MHA Helper'
long_description 'Installs/Configures MHA and MHA Helper'
version          '0.1.0'
